import React from 'react';
import { Page, Text, View, Document, StyleSheet, Font } from '@react-pdf/renderer';

// Register fonts if needed, for now standard Helvetica works for Swiss Style
// Font.register({ family: 'Inter', src: '...' });

const styles = StyleSheet.create({
    page: {
        flexDirection: 'column',
        backgroundColor: '#FFFFFF', // Swiss design loves white space
        padding: 40,
        fontFamily: 'Helvetica',
    },
    header: {
        fontSize: 10,
        color: '#94A3B8',
        marginBottom: 80,
        textTransform: 'uppercase',
        letterSpacing: 2,
    },
    titleSection: {
        marginBottom: 60,
    },
    title: {
        fontSize: 48,
        fontFamily: 'Helvetica-Bold',
        lineHeight: 1,
        color: '#0F172A',
    },
    subtitle: {
        marginTop: 10,
        fontSize: 18,
        color: '#64748B',
    },
    grid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginBottom: 60,
    },
    gridItem: {
        width: '50%',
        marginBottom: 30,
        paddingRight: 20,
    },
    label: {
        fontSize: 10,
        color: '#94A3B8',
        textTransform: 'uppercase',
        marginBottom: 5,
        letterSpacing: 1,
    },
    value: {
        fontSize: 24,
        color: '#0F172A',
        fontFamily: 'Helvetica-Bold',
    },
    quoteSection: {
        marginTop: 'auto',
        borderTop: '2px solid #0F172A',
        paddingTop: 20,
    },
    quote: {
        fontSize: 14,
        fontStyle: 'italic',
        color: '#334155',
        lineHeight: 1.5,
    },
    author: {
        marginTop: 10,
        fontSize: 10,
        fontWeight: 'bold',
        color: '#0F172A',
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 40,
        right: 40,
        flexDirection: 'row',
        justifyContent: 'space-between',
        fontSize: 8,
        color: '#CBD5E1',
    }
});

interface ManifestoProps {
    name?: string;
    birthDate: Date;
    stats: {
        years: string;
        days: string;
        breaths: string;
        heartbeats: string;
    }
}

export const ManifestoDocument = ({ name = "Traveler", birthDate, stats }: ManifestoProps) => {
    const quotes = [
        { text: "It is not that we have a short time to live, but that we waste a lot of it.", author: "Seneca" },
        { text: "Dost thou love life? Then do not squander time, for that's the stuff life is made of.", author: "Benjamin Franklin" },
        { text: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain" }
    ];
    const randomQuote = quotes[Math.floor(Math.random() * quotes.length)];

    return (
        <Document>
            <Page size="A4" style={styles.page}>
                <Text style={styles.header}>Ageinfo • Life Manifesto • {new Date().getFullYear()}</Text>

                <View style={styles.titleSection}>
                    <Text style={styles.title}>JEJAK WAKTU</Text>
                    <Text style={styles.subtitle}>{birthDate.toLocaleDateString('id-ID', { dateStyle: 'full' })}</Text>
                </View>

                <View style={styles.grid}>
                    <View style={styles.gridItem}>
                        <Text style={styles.label}>Total Years</Text>
                        <Text style={styles.value}>{stats.years}</Text>
                    </View>
                    <View style={styles.gridItem}>
                        <Text style={styles.label}>Days Lived</Text>
                        <Text style={styles.value}>{stats.days}</Text>
                    </View>
                    <View style={styles.gridItem}>
                        <Text style={styles.label}>Total Breaths (Est.)</Text>
                        <Text style={styles.value}>{stats.breaths}</Text>
                    </View>
                    <View style={styles.gridItem}>
                        <Text style={styles.label}>Heartbeats (Est.)</Text>
                        <Text style={styles.value}>{stats.heartbeats}</Text>
                    </View>
                </View>

                <View style={styles.quoteSection}>
                    <Text style={styles.quote}>"{randomQuote.text}"</Text>
                    <Text style={styles.author}>— {randomQuote.author}</Text>
                </View>

                <View style={styles.footer}>
                    <Text>Generated by Ageinfo.online</Text>
                    <Text>Veritas Temporis</Text>
                </View>
            </Page>
        </Document>
    );
};
