@echo off
echo Resetting Git...
git remote remove origin
git remote add origin https://github.com/Guns4/NewAgeInfo.git
echo Staging...
git add .
echo Committing...
git commit -m "chore: migrate to new repository and apply fixes"
echo Branching...
git branch -M main
echo Pushing...
git push -u origin main
echo Done.
